steps:
  - id: "Running Docker Compose"
    name: docker/compose
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
    dir: 'go-k8s'
  # - id: "Running Unit Tests"
  #   name: docker
  #   args: ['exec', '-t', 'golang_desafio_k8s', 'go', 'test', './...']
  - id: 'Build Image'
    name: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_NAME}', '.']
    dir: 'go-k8s'
substitutions:
  _GOLANG_FULLCYCLE_DESAFIO_K8S_NAME: 'golang_desafio_k8s:${_GOLANG_FULLCYCLE_DESAFIO_K8S_VERSION}'
  _GOLANG_FULLCYCLE_DESAFIO_K8S_VERSION: 1.0.0
images: ['gcr.io/$PROJECT_ID/${_GOLANG_FULLCYCLE_DESAFIO_K8S_NAME}']