steps:
  - id: "Running Docker Compose"
    name: docker/compose
    args: ['-f', 'go-k8s/docker-compose-ci.yml', 'up', '-d']
  - id: "Running Unit Tests"
    name: docker
    args: ['exec', '-t', 'golang_desafio_k8s', 'go', 'test', './...']
  - id: "List container dir"
    name: docker
    args: ['ls', '-lah']
  - id: "List volume dir"
    name: docker
    args: ['ls', '-lah', '/workspace/src']
  - id: 'Push Image'
    name: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/golang_desafio_k8s:${_GOLANG_FULLCYCLE_DESAFIO_K8S_VERSION}', '-f', 'src/desafio-k8s/go-k8s/Dockerfile-ci', '.']
substitutions:
  _GOLANG_FULLCYCLE_DESAFIO_K8S_VERSION: 1.0.0
images: ['gcr.io/$PROJECT_ID/golang_desafio_k8s:${_GOLANG_FULLCYCLE_DESAFIO_K8S_VERSION}']