apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-golang-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio-golang-k8s-deployment
      tier: backend
  template:
    metadata:
      labels:
        app: desafio-golang-k8s-deployment
        tier: backend
    spec:
      containers:
      - name: desafio-golang-k8s-pod
        image: andradereginaldo/code-education-desafio-k8s:latest
        ports:
          - containerPort: 8000