version: '3.7'

services:
    golang_desafio_k8s:
        build: 
            context: .
            dockerfile: Dockerfile-ci
        container_name: golang_desafio_k8s
        volumes:
            - .:/go/src/go-k8s
        expose:
            - "8000"
        ports: 
            - "8000:8000"
        networks:
            - desafio-go-k8s
networks:
    desafio-go-k8s:
        driver: bridge
